# Generated by Django 5.0.1 on 2024-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pesticide_time', models.DateTimeField()),
                ('migration_time', models.DateTimeField(blank=True, null=True)),
                ('harvesting_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='croptimeline',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='croptimeline',
            name='crop_type',
            field=models.CharField(choices=[('प्याज', 'प्याज'), ('टमाटर', 'टमाटर'), ('धान', 'धान')], max_length=100, unique=True),
        ),
    ]
